<?php
/**
 * EventRanking
 *
 * PHP version 5
 *
 * @category Class
 * @package  TBAAPI\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TBAAPI\v3client\TBAAPI\v3client\model;

use \ArrayAccess;
use \TBAAPI\v3client\ObjectSerializer;

/**
 * EventRanking Class Doc Comment
 *
 * @category Class
 * @package  TBAAPI\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventRanking implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Event_Ranking';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rankings' => '\TBAAPI\v3client\TBAAPI\v3client\model\EventRankingRankings[]',
        'extra_stats_info' => '\TBAAPI\v3client\TBAAPI\v3client\model\EventRankingExtraStatsInfo[]',
        'sort_order_info' => '\TBAAPI\v3client\TBAAPI\v3client\model\EventRankingSortOrderInfo[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'rankings' => null,
        'extra_stats_info' => null,
        'sort_order_info' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rankings' => 'rankings',
        'extra_stats_info' => 'extra_stats_info',
        'sort_order_info' => 'sort_order_info'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rankings' => 'setRankings',
        'extra_stats_info' => 'setExtraStatsInfo',
        'sort_order_info' => 'setSortOrderInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rankings' => 'getRankings',
        'extra_stats_info' => 'getExtraStatsInfo',
        'sort_order_info' => 'getSortOrderInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rankings'] = isset($data['rankings']) ? $data['rankings'] : null;
        $this->container['extra_stats_info'] = isset($data['extra_stats_info']) ? $data['extra_stats_info'] : null;
        $this->container['sort_order_info'] = isset($data['sort_order_info']) ? $data['sort_order_info'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rankings'] === null) {
            $invalidProperties[] = "'rankings' can't be null";
        }
        if ($this->container['sort_order_info'] === null) {
            $invalidProperties[] = "'sort_order_info' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rankings
     *
     * @return \TBAAPI\v3client\TBAAPI\v3client\model\EventRankingRankings[]
     */
    public function getRankings()
    {
        return $this->container['rankings'];
    }

    /**
     * Sets rankings
     *
     * @param \TBAAPI\v3client\TBAAPI\v3client\model\EventRankingRankings[] $rankings List of rankings at the event.
     *
     * @return $this
     */
    public function setRankings($rankings)
    {
        $this->container['rankings'] = $rankings;

        return $this;
    }

    /**
     * Gets extra_stats_info
     *
     * @return \TBAAPI\v3client\TBAAPI\v3client\model\EventRankingExtraStatsInfo[]|null
     */
    public function getExtraStatsInfo()
    {
        return $this->container['extra_stats_info'];
    }

    /**
     * Sets extra_stats_info
     *
     * @param \TBAAPI\v3client\TBAAPI\v3client\model\EventRankingExtraStatsInfo[]|null $extra_stats_info List of special TBA-generated values provided in the `extra_stats` array for each item.
     *
     * @return $this
     */
    public function setExtraStatsInfo($extra_stats_info)
    {
        $this->container['extra_stats_info'] = $extra_stats_info;

        return $this;
    }

    /**
     * Gets sort_order_info
     *
     * @return \TBAAPI\v3client\TBAAPI\v3client\model\EventRankingSortOrderInfo[]
     */
    public function getSortOrderInfo()
    {
        return $this->container['sort_order_info'];
    }

    /**
     * Sets sort_order_info
     *
     * @param \TBAAPI\v3client\TBAAPI\v3client\model\EventRankingSortOrderInfo[] $sort_order_info List of year-specific values provided in the `sort_orders` array for each team.
     *
     * @return $this
     */
    public function setSortOrderInfo($sort_order_info)
    {
        $this->container['sort_order_info'] = $sort_order_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


