<?php
/**
 * APIStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TBA-API\v3client;

use PHPUnit\Framework\TestCase;

/**
 * APIStatusTest Class Doc Comment
 *
 * @category    Class
 * @description APIStatus
 * @package     TBA-API\v3client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "APIStatus"
     */
    public function testAPIStatus()
    {
    }

    /**
     * Test attribute "current_season"
     */
    public function testPropertyCurrentSeason()
    {
    }

    /**
     * Test attribute "max_season"
     */
    public function testPropertyMaxSeason()
    {
    }

    /**
     * Test attribute "is_datafeed_down"
     */
    public function testPropertyIsDatafeedDown()
    {
    }

    /**
     * Test attribute "down_events"
     */
    public function testPropertyDownEvents()
    {
    }

    /**
     * Test attribute "ios"
     */
    public function testPropertyIos()
    {
    }

    /**
     * Test attribute "android"
     */
    public function testPropertyAndroid()
    {
    }
}
