<?php
/**
 * EventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TBA-API\v3client;

use PHPUnit\Framework\TestCase;

/**
 * EventTest Class Doc Comment
 *
 * @category    Class
 * @description Event
 * @package     TBA-API\v3client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EventTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Event"
     */
    public function testEvent()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "event_code"
     */
    public function testPropertyEventCode()
    {
    }

    /**
     * Test attribute "event_type"
     */
    public function testPropertyEventType()
    {
    }

    /**
     * Test attribute "district"
     */
    public function testPropertyDistrict()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state_prov"
     */
    public function testPropertyStateProv()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "short_name"
     */
    public function testPropertyShortName()
    {
    }

    /**
     * Test attribute "event_type_string"
     */
    public function testPropertyEventTypeString()
    {
    }

    /**
     * Test attribute "week"
     */
    public function testPropertyWeek()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "gmaps_place_id"
     */
    public function testPropertyGmapsPlaceId()
    {
    }

    /**
     * Test attribute "gmaps_url"
     */
    public function testPropertyGmapsUrl()
    {
    }

    /**
     * Test attribute "lat"
     */
    public function testPropertyLat()
    {
    }

    /**
     * Test attribute "lng"
     */
    public function testPropertyLng()
    {
    }

    /**
     * Test attribute "location_name"
     */
    public function testPropertyLocationName()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }

    /**
     * Test attribute "first_event_id"
     */
    public function testPropertyFirstEventId()
    {
    }

    /**
     * Test attribute "first_event_code"
     */
    public function testPropertyFirstEventCode()
    {
    }

    /**
     * Test attribute "webcasts"
     */
    public function testPropertyWebcasts()
    {
    }

    /**
     * Test attribute "division_keys"
     */
    public function testPropertyDivisionKeys()
    {
    }

    /**
     * Test attribute "parent_event_key"
     */
    public function testPropertyParentEventKey()
    {
    }

    /**
     * Test attribute "playoff_type"
     */
    public function testPropertyPlayoffType()
    {
    }

    /**
     * Test attribute "playoff_type_string"
     */
    public function testPropertyPlayoffTypeString()
    {
    }
}
