<?php
/**
 * EventInsights2018Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TBA-API\v3client;

use PHPUnit\Framework\TestCase;

/**
 * EventInsights2018Test Class Doc Comment
 *
 * @category    Class
 * @description Insights for FIRST Power Up qualification and elimination matches.
 * @package     TBA-API\v3client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EventInsights2018Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EventInsights2018"
     */
    public function testEventInsights2018()
    {
    }

    /**
     * Test attribute "auto_quest_achieved"
     */
    public function testPropertyAutoQuestAchieved()
    {
    }

    /**
     * Test attribute "average_boost_played"
     */
    public function testPropertyAverageBoostPlayed()
    {
    }

    /**
     * Test attribute "average_endgame_points"
     */
    public function testPropertyAverageEndgamePoints()
    {
    }

    /**
     * Test attribute "average_force_played"
     */
    public function testPropertyAverageForcePlayed()
    {
    }

    /**
     * Test attribute "average_foul_score"
     */
    public function testPropertyAverageFoulScore()
    {
    }

    /**
     * Test attribute "average_points_auto"
     */
    public function testPropertyAveragePointsAuto()
    {
    }

    /**
     * Test attribute "average_points_teleop"
     */
    public function testPropertyAveragePointsTeleop()
    {
    }

    /**
     * Test attribute "average_run_points_auto"
     */
    public function testPropertyAverageRunPointsAuto()
    {
    }

    /**
     * Test attribute "average_scale_ownership_points"
     */
    public function testPropertyAverageScaleOwnershipPoints()
    {
    }

    /**
     * Test attribute "average_scale_ownership_points_auto"
     */
    public function testPropertyAverageScaleOwnershipPointsAuto()
    {
    }

    /**
     * Test attribute "average_scale_ownership_points_teleop"
     */
    public function testPropertyAverageScaleOwnershipPointsTeleop()
    {
    }

    /**
     * Test attribute "average_score"
     */
    public function testPropertyAverageScore()
    {
    }

    /**
     * Test attribute "average_switch_ownership_points"
     */
    public function testPropertyAverageSwitchOwnershipPoints()
    {
    }

    /**
     * Test attribute "average_switch_ownership_points_auto"
     */
    public function testPropertyAverageSwitchOwnershipPointsAuto()
    {
    }

    /**
     * Test attribute "average_switch_ownership_points_teleop"
     */
    public function testPropertyAverageSwitchOwnershipPointsTeleop()
    {
    }

    /**
     * Test attribute "average_vault_points"
     */
    public function testPropertyAverageVaultPoints()
    {
    }

    /**
     * Test attribute "average_win_margin"
     */
    public function testPropertyAverageWinMargin()
    {
    }

    /**
     * Test attribute "average_win_score"
     */
    public function testPropertyAverageWinScore()
    {
    }

    /**
     * Test attribute "boost_played_counts"
     */
    public function testPropertyBoostPlayedCounts()
    {
    }

    /**
     * Test attribute "climb_counts"
     */
    public function testPropertyClimbCounts()
    {
    }

    /**
     * Test attribute "face_the_boss_achieved"
     */
    public function testPropertyFaceTheBossAchieved()
    {
    }

    /**
     * Test attribute "force_played_counts"
     */
    public function testPropertyForcePlayedCounts()
    {
    }

    /**
     * Test attribute "high_score"
     */
    public function testPropertyHighScore()
    {
    }

    /**
     * Test attribute "levitate_played_counts"
     */
    public function testPropertyLevitatePlayedCounts()
    {
    }

    /**
     * Test attribute "run_counts_auto"
     */
    public function testPropertyRunCountsAuto()
    {
    }

    /**
     * Test attribute "scale_neutral_percentage"
     */
    public function testPropertyScaleNeutralPercentage()
    {
    }

    /**
     * Test attribute "scale_neutral_percentage_auto"
     */
    public function testPropertyScaleNeutralPercentageAuto()
    {
    }

    /**
     * Test attribute "scale_neutral_percentage_teleop"
     */
    public function testPropertyScaleNeutralPercentageTeleop()
    {
    }

    /**
     * Test attribute "switch_owned_counts_auto"
     */
    public function testPropertySwitchOwnedCountsAuto()
    {
    }

    /**
     * Test attribute "unicorn_matches"
     */
    public function testPropertyUnicornMatches()
    {
    }

    /**
     * Test attribute "winning_opp_switch_denial_percentage_teleop"
     */
    public function testPropertyWinningOppSwitchDenialPercentageTeleop()
    {
    }

    /**
     * Test attribute "winning_own_switch_ownership_percentage"
     */
    public function testPropertyWinningOwnSwitchOwnershipPercentage()
    {
    }

    /**
     * Test attribute "winning_own_switch_ownership_percentage_auto"
     */
    public function testPropertyWinningOwnSwitchOwnershipPercentageAuto()
    {
    }

    /**
     * Test attribute "winning_own_switch_ownership_percentage_teleop"
     */
    public function testPropertyWinningOwnSwitchOwnershipPercentageTeleop()
    {
    }

    /**
     * Test attribute "winning_scale_ownership_percentage"
     */
    public function testPropertyWinningScaleOwnershipPercentage()
    {
    }

    /**
     * Test attribute "winning_scale_ownership_percentage_auto"
     */
    public function testPropertyWinningScaleOwnershipPercentageAuto()
    {
    }

    /**
     * Test attribute "winning_scale_ownership_percentage_teleop"
     */
    public function testPropertyWinningScaleOwnershipPercentageTeleop()
    {
    }
}
