<?php
/**
 * DistrictApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TBA-API\v3client;

use \TBA-API\v3client\Configuration;
use \TBA-API\v3client\ApiException;
use \TBA-API\v3client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DistrictApiTest Class Doc Comment
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DistrictApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getDistrictEvents
     *
     * .
     *
     */
    public function testGetDistrictEvents()
    {
    }

    /**
     * Test case for getDistrictEventsKeys
     *
     * .
     *
     */
    public function testGetDistrictEventsKeys()
    {
    }

    /**
     * Test case for getDistrictEventsSimple
     *
     * .
     *
     */
    public function testGetDistrictEventsSimple()
    {
    }

    /**
     * Test case for getDistrictRankings
     *
     * .
     *
     */
    public function testGetDistrictRankings()
    {
    }

    /**
     * Test case for getDistrictTeams
     *
     * .
     *
     */
    public function testGetDistrictTeams()
    {
    }

    /**
     * Test case for getDistrictTeamsKeys
     *
     * .
     *
     */
    public function testGetDistrictTeamsKeys()
    {
    }

    /**
     * Test case for getDistrictTeamsSimple
     *
     * .
     *
     */
    public function testGetDistrictTeamsSimple()
    {
    }

    /**
     * Test case for getDistrictsByYear
     *
     * .
     *
     */
    public function testGetDistrictsByYear()
    {
    }

    /**
     * Test case for getEventDistrictPoints
     *
     * .
     *
     */
    public function testGetEventDistrictPoints()
    {
    }

    /**
     * Test case for getTeamDistricts
     *
     * .
     *
     */
    public function testGetTeamDistricts()
    {
    }
}
