<?php
/**
 * TeamApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TBA-API\v3client;

use \TBA-API\v3client\Configuration;
use \TBA-API\v3client\ApiException;
use \TBA-API\v3client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamApiTest Class Doc Comment
 *
 * @category Class
 * @package  TBA-API\v3client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TeamApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getDistrictRankings
     *
     * .
     *
     */
    public function testGetDistrictRankings()
    {
    }

    /**
     * Test case for getDistrictTeams
     *
     * .
     *
     */
    public function testGetDistrictTeams()
    {
    }

    /**
     * Test case for getDistrictTeamsKeys
     *
     * .
     *
     */
    public function testGetDistrictTeamsKeys()
    {
    }

    /**
     * Test case for getDistrictTeamsSimple
     *
     * .
     *
     */
    public function testGetDistrictTeamsSimple()
    {
    }

    /**
     * Test case for getEventTeams
     *
     * .
     *
     */
    public function testGetEventTeams()
    {
    }

    /**
     * Test case for getEventTeamsKeys
     *
     * .
     *
     */
    public function testGetEventTeamsKeys()
    {
    }

    /**
     * Test case for getEventTeamsSimple
     *
     * .
     *
     */
    public function testGetEventTeamsSimple()
    {
    }

    /**
     * Test case for getEventTeamsStatuses
     *
     * .
     *
     */
    public function testGetEventTeamsStatuses()
    {
    }

    /**
     * Test case for getTeam
     *
     * .
     *
     */
    public function testGetTeam()
    {
    }

    /**
     * Test case for getTeamAwards
     *
     * .
     *
     */
    public function testGetTeamAwards()
    {
    }

    /**
     * Test case for getTeamAwardsByYear
     *
     * .
     *
     */
    public function testGetTeamAwardsByYear()
    {
    }

    /**
     * Test case for getTeamDistricts
     *
     * .
     *
     */
    public function testGetTeamDistricts()
    {
    }

    /**
     * Test case for getTeamEventAwards
     *
     * .
     *
     */
    public function testGetTeamEventAwards()
    {
    }

    /**
     * Test case for getTeamEventMatches
     *
     * .
     *
     */
    public function testGetTeamEventMatches()
    {
    }

    /**
     * Test case for getTeamEventMatchesKeys
     *
     * .
     *
     */
    public function testGetTeamEventMatchesKeys()
    {
    }

    /**
     * Test case for getTeamEventMatchesSimple
     *
     * .
     *
     */
    public function testGetTeamEventMatchesSimple()
    {
    }

    /**
     * Test case for getTeamEventStatus
     *
     * .
     *
     */
    public function testGetTeamEventStatus()
    {
    }

    /**
     * Test case for getTeamEvents
     *
     * .
     *
     */
    public function testGetTeamEvents()
    {
    }

    /**
     * Test case for getTeamEventsByYear
     *
     * .
     *
     */
    public function testGetTeamEventsByYear()
    {
    }

    /**
     * Test case for getTeamEventsByYearKeys
     *
     * .
     *
     */
    public function testGetTeamEventsByYearKeys()
    {
    }

    /**
     * Test case for getTeamEventsByYearSimple
     *
     * .
     *
     */
    public function testGetTeamEventsByYearSimple()
    {
    }

    /**
     * Test case for getTeamEventsKeys
     *
     * .
     *
     */
    public function testGetTeamEventsKeys()
    {
    }

    /**
     * Test case for getTeamEventsSimple
     *
     * .
     *
     */
    public function testGetTeamEventsSimple()
    {
    }

    /**
     * Test case for getTeamEventsStatusesByYear
     *
     * .
     *
     */
    public function testGetTeamEventsStatusesByYear()
    {
    }

    /**
     * Test case for getTeamMatchesByYear
     *
     * .
     *
     */
    public function testGetTeamMatchesByYear()
    {
    }

    /**
     * Test case for getTeamMatchesByYearKeys
     *
     * .
     *
     */
    public function testGetTeamMatchesByYearKeys()
    {
    }

    /**
     * Test case for getTeamMatchesByYearSimple
     *
     * .
     *
     */
    public function testGetTeamMatchesByYearSimple()
    {
    }

    /**
     * Test case for getTeamMediaByTag
     *
     * .
     *
     */
    public function testGetTeamMediaByTag()
    {
    }

    /**
     * Test case for getTeamMediaByTagYear
     *
     * .
     *
     */
    public function testGetTeamMediaByTagYear()
    {
    }

    /**
     * Test case for getTeamMediaByYear
     *
     * .
     *
     */
    public function testGetTeamMediaByYear()
    {
    }

    /**
     * Test case for getTeamRobots
     *
     * .
     *
     */
    public function testGetTeamRobots()
    {
    }

    /**
     * Test case for getTeamSimple
     *
     * .
     *
     */
    public function testGetTeamSimple()
    {
    }

    /**
     * Test case for getTeamSocialMedia
     *
     * .
     *
     */
    public function testGetTeamSocialMedia()
    {
    }

    /**
     * Test case for getTeamYearsParticipated
     *
     * .
     *
     */
    public function testGetTeamYearsParticipated()
    {
    }

    /**
     * Test case for getTeams
     *
     * .
     *
     */
    public function testGetTeams()
    {
    }

    /**
     * Test case for getTeamsByYear
     *
     * .
     *
     */
    public function testGetTeamsByYear()
    {
    }

    /**
     * Test case for getTeamsByYearKeys
     *
     * .
     *
     */
    public function testGetTeamsByYearKeys()
    {
    }

    /**
     * Test case for getTeamsByYearSimple
     *
     * .
     *
     */
    public function testGetTeamsByYearSimple()
    {
    }

    /**
     * Test case for getTeamsKeys
     *
     * .
     *
     */
    public function testGetTeamsKeys()
    {
    }

    /**
     * Test case for getTeamsSimple
     *
     * .
     *
     */
    public function testGetTeamsSimple()
    {
    }
}
